# Generated by Django 4.2.5 on 2023-09-27 15:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='Start_Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Task_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Progress', models.CharField(default='TODO', max_length=25)),
                ('Title', models.TextField()),
                ('Desc', models.TextField()),
                ('Alias_Assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
