name: Django CI/CD

on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]

jobs:
 build:

   runs-on: ubuntu-latest
   strategy:
     max-parallel: 4
     matrix:
       python-version: [3.11]

   steps:
   - uses: actions/checkout@v3
   - name: Set up Python ${{ matrix.python-version }}
     uses: actions/setup-python@v3
     with:
       python-version: ${{ matrix.python-version }}
   - name: Install Dependencies
     run: |
       python -m pip install --upgrade pip
       pip install -r requirements.txt
   - name: Run Tests
     env:
       ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
       SECRET_KEY: ${{ secrets.SECRET_KEY }}
       DATABASE_URL: ${{ secrets.DATABASE_URL }}
       DEBUG: ${{ secrets.DEBUG }}
     run: |
       python manage.py test
 deploy:
   name: Deploy
   needs: [build]
   runs-on: ubuntu-latest

   steps: 
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }} # Can be found as part of the Deploy Hook
          api-key: ${{ secrets.RENDER_API_KEY }} # Create your API key in Render Dashboard > Account Settings
